'use client';

import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {useEffect, useState} from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [bodyClassName, setBodyClassName] = useState(
    `${geistSans.variable} ${geistMono.variable} antialiased`
  );

  useEffect(() => {
    setBodyClassName(`${geistSans.variable} ${geistMono.variable} antialiased`);
  }, []);

  return (
    <html lang="en">
      <body className={bodyClassName}>
        {children}
      </body>
    </html>
  );
}

